version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    dns: 
      - 127.0.0.1
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    env_file:
      - stack.env
    environment:
      TZ: "Europe/Amsterdam"
      DNSMASQ_USER: "pihole"
      FTL_CMD: "no-daemon"
      FTLCONF_LOCAL_IPV4: "0.0.0.0"
      PHP_ERROR_LOG: "/var/log/lighttpd/error-pihole.log"
      PIHOLE_DNS_: "172.20.0.100#5053"
    volumes:
      - /opt/portainer/pihole-dnsmasq.d:/etc/dnsmasq.d
      - /opt/portainer/pihole:/etc/pihole

    networks:
      pihole_net:
        ipv4_address: 172.20.0.101

  cloudflared:
    image: cloudflare/cloudflared:2024.2.0
    restart: unless-stopped
    container_name: cloudflared
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: "https://1.0.0.1/dns-query,https://1.1.1.1/dns-query"
      TUNNEL_DNS_PORT: "5053"
      TUNNEL_DNS_ADDRESS: "0.0.0.0"
    networks:
      pihole_net:
        ipv4_address: 172.20.0.100

networks:
  pihole_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/20"
          gateway: "172.20.0.1"
